export { default as HomePage } from './HomePage'
export { default as PricePage } from './PricePage'
export { default as SpecialPage } from './SpecialPage'
export { default as FaqPage } from './FaqPage'
export { default as ContactPage } from './ContactPage'
export { default as ReservePage } from './ReservePage'